/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opencv_OpenCVJni */

#ifndef _Included_com_opencv_OpenCVJni
#define _Included_com_opencv_OpenCVJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opencv_OpenCVJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_opencv_OpenCVJni_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    initHistParam
 * Signature: (II[F[F)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_initHistParam
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    getHistFeatureFromImage
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_getHistFeatureFromImage
  (JNIEnv *, jobject, jstring, jfloatArray, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    compareHistFeature
 * Signature: ([F[FIDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opencv_OpenCVJni_compareHistFeature
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jdouble, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    getHashCodeFromImageByte
 * Signature: (Ljava/lang/String;[ZII)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_getHashCodeFromImageByte
  (JNIEnv *, jobject, jstring, jbooleanArray, jint, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    getHashCodeFromImageDouble
 * Signature: (Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_getHashCodeFromImageDouble
  (JNIEnv *, jobject, jstring, jdoubleArray, jint, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    compareHashCodeByte
 * Signature: ([Z[ZIDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opencv_OpenCVJni_compareHashCodeByte
  (JNIEnv *, jobject, jbooleanArray, jbooleanArray, jint, jdouble, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    compareHashCodeDouble
 * Signature: ([D[DIDI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opencv_OpenCVJni_compareHashCodeDouble
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jdouble, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    printHistFeature
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_printHistFeature
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    printHashCodeBype
 * Signature: ([ZI)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_printHashCodeBype
  (JNIEnv *, jobject, jbooleanArray, jint);

/*
 * Class:     com_opencv_OpenCVJni
 * Method:    printHashCodeDouble
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_com_opencv_OpenCVJni_printHashCodeDouble
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
