#ifndef _DEF_TYPE_H
#define _DEF_TYPE_H


#define ERROR_COMPARE_RESULT -1000.0

enum G_HIST_TYPE {
	G_COLOR_HIST, 
	G_GRAY_HIST,
	G_OTHER_HIST
};

enum CompareType {
	G_HIST_COMPARE,
	G_HASH_COMPARE,
	G_OTHER_COMPARE
};

// 0: CV_COMP_CORREL		[-1, 1] 1 
// 1: CV_COMP_CHISQR		[--, 0] 0
// 2: CV_COMP_INTERSECT		
// 3: CV_COMP_BHATTACHARYYA	[ 0, 1] 0 
// 4: CV_COMP_HELLINGER		[-1, 1] 1
// 5: CV_COMP_CHISQR_ALT			
// 6: CV_COMP_KL_DIV	
// 7: EMD
enum HistMethodType {
	H_CV_COMP_CORREL, 
	H_CV_COMP_CHISQR,
	H_CV_COMP_INTERSECT,
	H_CV_COMP_BHATTACHARYYA, 
	H_CV_COMP_HELLINGER, 
	H_CV_COMP_CHISQR_ALT, 
	H_CV_COMP_KL_DIV, 
	H_CV_EMD     // unusable
};

enum HashMethodType {
	G_HASH_AVERAGE,
	G_HASH_P,
	G_HASH_MARR_HILDREN,
	G_HASH_RADIAL_VARIANCE,
	G_HASH_BLOCK_MEAN,
	G_HASH_COLOR_MOMENT,
	G_HASH_OTHER
};

#endif //_DEF_TYPE_H